INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) VALUES ('Jack', 'Bauer', 'j.bauer@ctu.gov', '$2a$10$pSMyxs/5EEU3CCOwUC.RTuDfUL8kSiryHXOqj0m8H./IW9XrNOtlG')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) VALUES ('Chloe','O`Brian', 'c.obrian@ctu.gov', '$2a$10$pSMyxs/5EEU3CCOwUC.RTuDfUL8kSiryHXOqj0m8H./IW9XrNOtlG')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) VALUES ('Kim', 'Bauer', 'kim_bauer@gmail.com', '$2a$10$pSMyxs/5EEU3CCOwUC.RTuDfUL8kSiryHXOqj0m8H./IW9XrNOtlG')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) VALUES ('Tony', 'Almeida', 't.almeida@ctu.gov', '$2a$10$pSMyxs/5EEU3CCOwUC.RTuDfUL8kSiryHXOqj0m8H./IW9XrNOtlG')



