INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) VALUES ('Jack', 'Bauer', 'j.bauer@ctu.gov', '$2a$10$pSMyxs/5EEU3CCOwUC.RTuDfUL8kSiryHXOqj0m8H./IW9XrNOtlG')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) VALUES ('Chloe','O`Brian', 'c.obrian@ctu.gov', '$2a$10$pSMyxs/5EEU3CCOwUC.RTuDfUL8kSiryHXOqj0m8H./IW9XrNOtlG')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) VALUES ('Kim', 'Bauer', 'kim_bauer@gmail.com', '$2a$10$pSMyxs/5EEU3CCOwUC.RTuDfUL8kSiryHXOqj0m8H./IW9XrNOtlG')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) VALUES ('Tony', 'Almeida', 't.almeida@ctu.gov', '$2a$10$pSMyxs/5EEU3CCOwUC.RTuDfUL8kSiryHXOqj0m8H./IW9XrNOtlG')



INSERT INTO GAME (creation_date) VALUES ('2019-07-03 15:34:41.123')
INSERT INTO GAME (creation_date) VALUES ('2019-07-03 16:34:41.123')

INSERT INTO GAME_PLAYER (player_id, game_id) VALUES (1, 1)
INSERT INTO GAME_PLAYER (player_id, game_id) VALUES (2, 1)

INSERT INTO SHIP (ship_type, game_player_id_id) VALUES ('BARCO_1',1)
INSERT INTO SHIP_LOCATION(SHIP_ID, LOCATION)values (1,'A1')
INSERT INTO SHIP_LOCATION(SHIP_ID, LOCATION)values (1,'A2')
INSERT INTO SHIP_LOCATION(SHIP_ID, LOCATION)values (1,'A3')
INSERT INTO SHIP_LOCATION(SHIP_ID, LOCATION)values (1,'A4')
INSERT INTO SHIP_LOCATION(SHIP_ID, LOCATION)values (1,'A5')

INSERT INTO SALVO (game_player_id, turn)values (1,1)
